### ISSUE TITLE
`ribose file add` command outputs errors even when it succeeds

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/ribose-cli#60]
```sh
ribose file add -s xxx-xxx-xxx-xxx my-document.pdf 
```

Error:
```
/usr/share/rubies/versions/2.4.3/lib/ruby/gems/2.4.0/gems/ribose-0.2.0/lib/ribose/space_file.rb:30:in `[]': no implicit conversion of Symbol into Integer (TypeError)
	from /usr/share/rubies/versions/2.4.3/lib/ruby/gems/2.4.0/gems/ribose-0.2.0/lib/ribose/space_file.rb:30:in `create'
	from /usr/share/rubies/versions/2.4.3/lib/ruby/gems/2.4.0/gems/ribose-cli-0.2.0/lib/ribose/cli/commands/file.rb:66:in `create_upload'
	from /usr/share/rubies/versions/2.4.3/lib/ruby/gems/2.4.0/gems/ribose-cli-0.2.0/lib/ribose/cli/commands/file.rb:29:in `add'
	from /usr/share/rubies/versions/2.4.3/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /usr/share/rubies/versions/2.4.3/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/share/rubies/versions/2.4.3/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /usr/share/rubies/versions/2.4.3/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:115:in `invoke'
	from /usr/share/rubies/versions/2.4.3/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor.rb:242:in `block in subcommand'
	from /usr/share/rubies/versions/2.4.3/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /usr/share/rubies/versions/2.4.3/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/share/rubies/versions/2.4.3/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /usr/share/rubies/versions/2.4.3/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /usr/share/rubies/versions/2.4.3/lib/ruby/gems/2.4.0/gems/ribose-cli-0.2.0/lib/ribose/cli.rb:12:in `start'
	from /usr/share/rubies/versions/2.4.3/lib/ruby/gems/2.4.0/gems/ribose-cli-0.2.0/bin/ribose:22:in `<top (required)>'
	from /usr/share/rubies/versions/2.4.3/bin/ribose:23:in `load'
	from /usr/share/rubies/versions/2.4.3/bin/ribose:23:in `<main>'
```

It's actually uploaded and can be shown via `ribose file list -s xxx-xxx-xxx-xxx`

**Comment by abunashir** [comment]
@ronaldtse, This is related to https://github.com/riboseinc/ribose-ruby/issues/131, once that's fixed that this should also work fine :)

**Comment by ronaldtse** [comment]
Excellent! 👍

**Comment by ronaldtse** [comment]
Thanks @abunashir !
